
package backgammon;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author mertarmagan
 */
public class SettingsMenu extends javax.swing.JPanel {
    
    private JPanel mainPanel;
    private JFrame mainFrame;
    
    
    private boolean soundOnSelected;
    private boolean soundOffSelected;
    
    public SettingsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        soundOnBtn = new javax.swing.JButton();
        soundOffBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setText("Back");
        back.setFocusPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SOUND:");

        jLabel2.setFont(new java.awt.Font("Lithos Pro Regular", 0, 50)); // NOI18N
        jLabel2.setText("SETTINGS");

        soundOnBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soundOnBtn.setText("ON");
        soundOnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOnBtnActionPerformed(evt);
            }
        });

        soundOffBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soundOffBtn.setText("OFF");
        soundOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOffBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(back)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(soundOnBtn)
                        .addGap(18, 18, 18)
                        .addComponent(soundOffBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(jLabel2))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(soundOnBtn)
                        .addComponent(soundOffBtn)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        mainFrame.setContentPane(mainPanel);
        
        mainFrame.invalidate();
        mainFrame.validate();
    }//GEN-LAST:event_backActionPerformed

    private void soundOnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundOnBtnActionPerformed
        // TODO add your handling code here:
        soundOnSelected = true;
        soundOffSelected = false;
        
        soundOnBtn.setEnabled(false);
        soundOffBtn.setEnabled(true);
    }//GEN-LAST:event_soundOnBtnActionPerformed

    private void soundOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundOffBtnActionPerformed
        // TODO add your handling code here:
        soundOnSelected = false;
        soundOffSelected = true;
        
        soundOnBtn.setEnabled(true);
        soundOffBtn.setEnabled(false);
    }//GEN-LAST:event_soundOffBtnActionPerformed
    
    public void setMainMenu(JPanel mainPanel){      
       this.mainPanel =  mainPanel;
    }
    
    public void setMainFrame(JFrame mainFrame){
        this.mainFrame = mainFrame;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton soundOffBtn;
    private javax.swing.JButton soundOnBtn;
    // End of variables declaration//GEN-END:variables
}
